name: CI/CD Money Saver API

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # ================= JOB 1: RUN TESTS =================
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres_test:
        image: postgres:16-alpine
        env:
          # Ini env internal untuk container Postgres tiruan di GitHub (wajib sinkron dengan Go)
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: azmi123
          POSTGRES_DB: money_saver_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Sesuai request lu cuy, udah gua ganti ke 1.25
          cache: true

      - name: Run Go Unit & Integration Tests
        # Di sini nama ENV KANAN kiri WAJIB disamain dengan os.Getenv() di file db_setup.go lu!
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: azmi123
          TEST_DB_NAME: money_saver_test
          APP_ENV: test
        run: |
          echo "🧪 Menjalankan Unit Test dan Integration Test di GitHub Runner..."
          go test -v -p 1 ./...

  # ================= JOB 2: DEPLOY TO VPS =================
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🤖 Menghubungi VPS... Koneksi Berhasil!"
            cd /root/app-money-saver
            echo "📥 Mengambil update kodingan terbaru..."
            git pull origin main
            echo "🚀 Memulai proses Build & Restart Docker Container..."
            docker compose up -d --build
            echo "🧹 Bersihkan image menggantung..."
            docker system prune -f
            echo "✅ DEPLOYMENT SUKSES TOTAL CUY!"